// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB813rMjjJAKd5z1yWG34W55X9g85_Cu-I',
    appId: '1:60417216583:web:493c129d71dcdd4b3be162',
    messagingSenderId: '60417216583',
    projectId: 'students-course-rodrigopaz',
    authDomain: 'students-course-rodrigopaz.firebaseapp.com',
    storageBucket: 'students-course-rodrigopaz.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDORuCs9EJb9QHn8noNUKjBPyuYBZCtIU8',
    appId: '1:60417216583:android:371ba87d41ab91a13be162',
    messagingSenderId: '60417216583',
    projectId: 'students-course-rodrigopaz',
    storageBucket: 'students-course-rodrigopaz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrlqzvlpmtqnTZe9LsDp19GP_O8EAakGk',
    appId: '1:60417216583:ios:550055d4d1193a313be162',
    messagingSenderId: '60417216583',
    projectId: 'students-course-rodrigopaz',
    storageBucket: 'students-course-rodrigopaz.firebasestorage.app',
    iosBundleId: 'com.rodrigopaz.estudianteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrlqzvlpmtqnTZe9LsDp19GP_O8EAakGk',
    appId: '1:60417216583:ios:550055d4d1193a313be162',
    messagingSenderId: '60417216583',
    projectId: 'students-course-rodrigopaz',
    storageBucket: 'students-course-rodrigopaz.firebasestorage.app',
    iosBundleId: 'com.rodrigopaz.estudianteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB813rMjjJAKd5z1yWG34W55X9g85_Cu-I',
    appId: '1:60417216583:web:1aa9ea91a4291ae73be162',
    messagingSenderId: '60417216583',
    projectId: 'students-course-rodrigopaz',
    authDomain: 'students-course-rodrigopaz.firebaseapp.com',
    storageBucket: 'students-course-rodrigopaz.firebasestorage.app',
  );
}
